// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iyistxtmklcbpfaigthy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml5aXN0eHRta2xjYnBmYWlndGh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2ODc1NDEsImV4cCI6MjA2NjI2MzU0MX0.k5Lzdy7vXPfLYzNDgjUquUFjjECBNf_SLRGvlUpGux8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);